ProTwo/ProTwo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from app_two import views

urlpatterns = [
    path('', views.home, name="home"),
    path('registration/', views.register, name="register"),
    path('App2/', include('app_two.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
]

ProTwo/app_two/urls.py
from django.urls import path
from app_two import views

app_name = "Apptwo"

urlpatterns = [

    path('app_two_home/', views.two_home, name="two_home"),
    path('help/', views.help, name="help"),
    path('users/', views.users, name="users"),
    path('form/', views.form_one, name="form"),

]

ProTwo/app_two/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class MyUser(models.Model):
    first_name = models.CharField(max_length=264)
    last_name = models.CharField(max_length=264)
    email = models.EmailField(max_length=264, unique=True)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    profile_site = models.URLField(blank=True)
    profile_photo = models.ImageField(upload_to="profile_images", blank=True)

    def __str__(self):
        return self.user.username

ProTwo/app_two/forms.py
from django import forms
from django.contrib.auth.models import User
from app_two.models import MyUser, Profile


class FormOne(forms.ModelForm):

    class Meta:
        model = MyUser
        fields = '__all__'


class ProfileInForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class ProfileExtendForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('profile_site', 'profile_photo')

ProTwo/app_two/views.py
from django.shortcuts import render
from django.http import HttpResponse
from app_two.models import MyUser, Profile
from app_two.forms import FormOne, ProfileInForm, ProfileExtendForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, "home.html")


def two_home(request):
    return render(request, "app_two/home.html")


def help(request):
    dict = {"my_variable": "Help page"}
    return render(request,"app_two/help.html",context = dict)


def users(request):
    u_dict = {"user": MyUser.objects.all()}
    return render(request, "app_two/mtv.html", context=u_dict)


def form_one(request):
    form = FormOne()

    if request.method == 'POST':
        form = FormOne(request.POST)

        if form.is_valid():
            # DO SOMETHING CODE
            form.save(commit=True)
            return home(request)
        else:
            print('ERROR FORM INVALID')

    return render(request, 'app_two/users.html', {'form': form})


def register(request):

    registered = False

    if request.method == 'POST':
        profile_in_form = ProfileInForm(request.POST)
        profile_extend_form = ProfileExtendForm(request.POST)

        if profile_in_form.is_valid() and profile_extend_form.is_valid():

            user = profile_in_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_extend_form.save(commit=False)
            profile.user = user

            if 'profile_photo' in request.FILES:
                print('found it')
                profile.profile_photo = request.FILES['profile_photo']

                profile.save()
            registered = True
        else:
            print(profile_in_form.errors, profile_extend_form.errors)

    else:
        profile_in_form = ProfileInForm()
        profile_extend_form = ProfileExtendForm()

    return render(request, 'register.html', {'registered': registered, 'profile_in_form': profile_in_form , 'profile_extend_form': profile_extend_form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse('YOU ARE INACTIVE')
        else:
            print('This username {} and password {} combination failed '.format(username, password))
            return HttpResponse('Invalid Credentials')
    else:
        return render(request, 'login.html')

ProTwo/templates/app_two/help.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load filter %}
{% block head_block %}
<title>Help Page</title>
{% endblock %}

    {% block body_block %}
    <h1>This is my {{ my_variable|cut:"help" }} from app_two</h1>
    <br>
    <button type="button" name="home"><a href="/">Home</a></button>
    {% endblock %}

ProTwo/templates/app_two/home.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}

{% block head_block %}
  <title>JeevanJyothi</title>
{% endblock %}

{% block body_block %}
    <h1>Welcome to Jeevan Jyothi Application</h1>
    <br><br>
    <img src="{% static "images/ours.jpg" %}" alt="image not found">
    <br><br><br>

    <button type="button" name="help"><a href="{% url 'Apptwo:help' %}">help</a></button>
    <button type="button" name="users"><a href="{% url 'Apptwo:users' %}">users</a></button>
    <button type="button" name="users"><a href="{% url 'Apptwo:form' %}">form</a></button>
{% endblock %}

ProTwo/templates/app_two/mtv.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block head_block %}
<title>Users</title>
{% endblock %}

{% block body_block %}
<h1>Here are your users:</h1>

{% if user %}
<table>
    <tbody>
    <th colspan=" 100 "> User Information</th>

    <tr>
        <td>First Name</td>
        <td>Last Name</td>
        <td>Email :</td>
    </tr>

    {% for u in user %}

    <tr>
        <td>{{ u.first_name }}</td>
        <td>{{ u.last_name }}</td>
        <td>{{ u.email}}</td>
    </tr>

    {% endfor %}
    </tbody>
</table>

{% endif %}
{% endblock %}

ProTwo/templates/app_two/users.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block head_block %}
<title>Form</title>
{% endblock %}

<body>
{% block body_block %}
<div class="container">
    <h1>Please sign up here!</h1>
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class='btn btn-primary' value="Submit">
    </form>
</div>
{% endblock %}

ProTwo/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>

    <meta charset="utf-8">

    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "css/apptwo.css" %}">

    {% block head_block %}
    <title>Base</title>
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-item nav-link" href="{% url 'register' %}">registration</a>
        <a class="nav-item nav-link" href="{% url 'Apptwo:two_home' %}">app_two_home</a>
        <a class="nav-item nav-link" href="{% url 'Apptwo:help' %}">help</a>
        <a class="nav-item nav-link" href="{% url 'Apptwo:users' %}">users</a>
        <a class="nav-item nav-link" href="{% url 'Apptwo:form' %}">form</a>


    </div>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link " href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                {% endif %}
            </li>
        </ul>
    </div>

</nav>


<div class="container">

    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
</div>

</body>
</html>

ProTwo/templates/home.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block head_block %}
    <title>Home Page</title>
{% endblock %}

{% block body_block %}
      <div class="container">
      <div class="jumbotron">
          <h1>PROJECT TWO</h1><br>
        <p>It has only one application "app_two"</p><br><br>
        {% if user.is_authenticated %}
            <h2>Welcome {{ user.username }}!</h2>
        {% else %}
            <h2>Welcome to the site!</h2>
        {% endif %}
      </div>
    </div>

{% endblock %}

ProTwo/templates/login.html
{% extends "base.html" %}

{% block head_block %}
    <title>Login Page</title>
{% endblock %}

{% block body_block %}
<div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'login' %}">
          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>

{% endblock %}

ProTwo/templates/register.html
{% extends "base.html" %}

{% block head_block %}
    <title>Registration page</title>
{% endblock %}

{% block body_block %}
    {% if registered %}
        <p><strong>*********  Thank you for registering!  ********* </strong><p>
    {% else %}
        <form enctype="multipart/form-data" method="POST">

            {% csrf_token %}
            {{ profile_in_form.as_p }}
            {{ profile_extend_form.as_p }}

            <input type="submit" name="register" value="Submit">

        </form>

    {% endif %}

{% endblock %}